---
title: Tolenas Winery
description: Family. Focused on Quality. Suisun Valley CA.
meta_img: /img/tolenas-meta.jpg
twitter:
favicon: /img/tolenas-favicon.png
url: https://tolenaswinery.com
gtm: GTM-TN69QNC
age-gate: true
schema:
  name: Tolenas Winery
  type: Business
  image: /img/tolenas-meta.jpg
  logo:  /img/Tolenas-Gold.jpg
  phone: 
  email: 
  social:
  - https://www.facebook.com/tolenaswinery/
  - https://www.instagram.com/tolenaswinery/?hl=en
  location: 
    address: 4185 Chadbourne RD
    city: Fairfield  
    state: CA
    zip: 94534
  hours:
    days:
    opens:
    closes:  
timezone: America/Los_Angeles
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-liquify
collections:
  terms:
    output: true
  pages: 
    output: true  
  redirects:
    output: true  
defaults:
- scope:
    type: 'pages'
  values:
    layout: page
- scope:
    type: 'redirects' 
  values:
    layout: redirect
    sitemap: false  
- scope: 
    path: '_pages/reservation.md'
  values:
    layout: reservation        
